package br.com.mechanic.mechanic.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    INVALID_USER_INPUT,
    DATABASE_ERROR,
    INTERNAL_ERROR,
    ERROR_CREATED_USER,
    INACTIVE_ERROR, INVALID_FIELD, EMAIL_ALREADY_EXISTS, ERROR_CREATED_CLIENT,IDENTICAL_FIELDS, ERROR_CLIENT_NOT_FOUND, PHONE_NUMBER_ALREADY_EXISTS, ERROR_CREATED_RAFFLE_NAME, ERROR_RAFFLE_NAME_NOT_FOUND, RAFFLE_NAME_ALREADY_EXISTS, RAFFLE_CAMPAIGN_LINK_ALREADY_EXISTS, START_DATE_INVALID, CANOT_CHANGE_STATUS, CANNOT_CHANGE_STATUS, ERROR_RAFFLE_NOT_FOUND, ERROR_CAMPAIGN_NOT_FOUND, CAMPAIGN_ALREADY_EXISTS, ERROR_CLIENT_INVALID, CAMPAIGN_IS_EMPTY, ERROR_PURCHASED_NAME_NOT_FOUND, ERROR_CAMPAIGN_FOUND, ERROR_CHANGE_STATUS, ERROR_RAFFLE_WINNER_NOT_FOUND, ERROR_PROVIDER_ACCOUNT_NOT_FOUND, ERROR_CREATED_ADDRESS, ERROR_PROVIDER_ACCOUNT_TYPE_NOT_FOUND, ERROR_CREATED_PHONE;
}
